/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.dabz.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Record extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6680864886778919170L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Record\",\"namespace\":\"io.confluent.dabz.model\",\"fields\":[{\"name\":\"line\",\"type\":\"string\",\"doc\":\"a line?\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Record> ENCODER =
      new BinaryMessageEncoder<Record>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Record> DECODER =
      new BinaryMessageDecoder<Record>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Record> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Record> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Record>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Record to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Record from a ByteBuffer. */
  public static Record fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** a line? */
  @Deprecated public java.lang.CharSequence line;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Record() {}

  /**
   * All-args constructor.
   * @param line a line?
   */
  public Record(java.lang.CharSequence line) {
    this.line = line;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return line;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: line = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'line' field.
   * @return a line?
   */
  public java.lang.CharSequence getLine() {
    return line;
  }

  /**
   * Sets the value of the 'line' field.
   * a line?
   * @param value the value to set.
   */
  public void setLine(java.lang.CharSequence value) {
    this.line = value;
  }

  /**
   * Creates a new Record RecordBuilder.
   * @return A new Record RecordBuilder
   */
  public static io.confluent.dabz.model.Record.Builder newBuilder() {
    return new io.confluent.dabz.model.Record.Builder();
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Record RecordBuilder
   */
  public static io.confluent.dabz.model.Record.Builder newBuilder(io.confluent.dabz.model.Record.Builder other) {
    return new io.confluent.dabz.model.Record.Builder(other);
  }

  /**
   * Creates a new Record RecordBuilder by copying an existing Record instance.
   * @param other The existing instance to copy.
   * @return A new Record RecordBuilder
   */
  public static io.confluent.dabz.model.Record.Builder newBuilder(io.confluent.dabz.model.Record other) {
    return new io.confluent.dabz.model.Record.Builder(other);
  }

  /**
   * RecordBuilder for Record instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Record>
    implements org.apache.avro.data.RecordBuilder<Record> {

    /** a line? */
    private java.lang.CharSequence line;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.dabz.model.Record.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Record instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.dabz.model.Record other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.line)) {
        this.line = data().deepCopy(fields()[0].schema(), other.line);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'line' field.
      * a line?
      * @return The value.
      */
    public java.lang.CharSequence getLine() {
      return line;
    }

    /**
      * Sets the value of the 'line' field.
      * a line?
      * @param value The value of 'line'.
      * @return This builder.
      */
    public io.confluent.dabz.model.Record.Builder setLine(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.line = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'line' field has been set.
      * a line?
      * @return True if the 'line' field has been set, false otherwise.
      */
    public boolean hasLine() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'line' field.
      * a line?
      * @return This builder.
      */
    public io.confluent.dabz.model.Record.Builder clearLine() {
      line = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Record build() {
      try {
        Record record = new Record();
        record.line = fieldSetFlags()[0] ? this.line : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Record>
    WRITER$ = (org.apache.avro.io.DatumWriter<Record>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Record>
    READER$ = (org.apache.avro.io.DatumReader<Record>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
