/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.dabz.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class VisitEventAggregatedValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3877582227389896163L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VisitEventAggregatedValue\",\"namespace\":\"io.confluent.dabz.model\",\"fields\":[{\"name\":\"page\",\"type\":\"string\",\"doc\":\"page that has been visited\"},{\"name\":\"date\",\"type\":\"long\",\"doc\":\"time of the aggregated window\",\"logicalType\":\"time-millis\"},{\"name\":\"duration\",\"type\":\"int\",\"doc\":\"duration of the aggregation\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<VisitEventAggregatedValue> ENCODER =
      new BinaryMessageEncoder<VisitEventAggregatedValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VisitEventAggregatedValue> DECODER =
      new BinaryMessageDecoder<VisitEventAggregatedValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<VisitEventAggregatedValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<VisitEventAggregatedValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<VisitEventAggregatedValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this VisitEventAggregatedValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a VisitEventAggregatedValue from a ByteBuffer. */
  public static VisitEventAggregatedValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** page that has been visited */
  @Deprecated public java.lang.CharSequence page;
  /** time of the aggregated window */
  @Deprecated public long date;
  /** duration of the aggregation */
  @Deprecated public int duration;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VisitEventAggregatedValue() {}

  /**
   * All-args constructor.
   * @param page page that has been visited
   * @param date time of the aggregated window
   * @param duration duration of the aggregation
   */
  public VisitEventAggregatedValue(java.lang.CharSequence page, java.lang.Long date, java.lang.Integer duration) {
    this.page = page;
    this.date = date;
    this.duration = duration;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return page;
    case 1: return date;
    case 2: return duration;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: page = (java.lang.CharSequence)value$; break;
    case 1: date = (java.lang.Long)value$; break;
    case 2: duration = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'page' field.
   * @return page that has been visited
   */
  public java.lang.CharSequence getPage() {
    return page;
  }

  /**
   * Sets the value of the 'page' field.
   * page that has been visited
   * @param value the value to set.
   */
  public void setPage(java.lang.CharSequence value) {
    this.page = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return time of the aggregated window
   */
  public java.lang.Long getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * time of the aggregated window
   * @param value the value to set.
   */
  public void setDate(java.lang.Long value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return duration of the aggregation
   */
  public java.lang.Integer getDuration() {
    return duration;
  }

  /**
   * Sets the value of the 'duration' field.
   * duration of the aggregation
   * @param value the value to set.
   */
  public void setDuration(java.lang.Integer value) {
    this.duration = value;
  }

  /**
   * Creates a new VisitEventAggregatedValue RecordBuilder.
   * @return A new VisitEventAggregatedValue RecordBuilder
   */
  public static io.confluent.dabz.model.VisitEventAggregatedValue.Builder newBuilder() {
    return new io.confluent.dabz.model.VisitEventAggregatedValue.Builder();
  }

  /**
   * Creates a new VisitEventAggregatedValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VisitEventAggregatedValue RecordBuilder
   */
  public static io.confluent.dabz.model.VisitEventAggregatedValue.Builder newBuilder(io.confluent.dabz.model.VisitEventAggregatedValue.Builder other) {
    return new io.confluent.dabz.model.VisitEventAggregatedValue.Builder(other);
  }

  /**
   * Creates a new VisitEventAggregatedValue RecordBuilder by copying an existing VisitEventAggregatedValue instance.
   * @param other The existing instance to copy.
   * @return A new VisitEventAggregatedValue RecordBuilder
   */
  public static io.confluent.dabz.model.VisitEventAggregatedValue.Builder newBuilder(io.confluent.dabz.model.VisitEventAggregatedValue other) {
    return new io.confluent.dabz.model.VisitEventAggregatedValue.Builder(other);
  }

  /**
   * RecordBuilder for VisitEventAggregatedValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VisitEventAggregatedValue>
    implements org.apache.avro.data.RecordBuilder<VisitEventAggregatedValue> {

    /** page that has been visited */
    private java.lang.CharSequence page;
    /** time of the aggregated window */
    private long date;
    /** duration of the aggregation */
    private int duration;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.dabz.model.VisitEventAggregatedValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.page)) {
        this.page = data().deepCopy(fields()[0].schema(), other.page);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing VisitEventAggregatedValue instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.dabz.model.VisitEventAggregatedValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.page)) {
        this.page = data().deepCopy(fields()[0].schema(), other.page);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.duration)) {
        this.duration = data().deepCopy(fields()[2].schema(), other.duration);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'page' field.
      * page that has been visited
      * @return The value.
      */
    public java.lang.CharSequence getPage() {
      return page;
    }

    /**
      * Sets the value of the 'page' field.
      * page that has been visited
      * @param value The value of 'page'.
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder setPage(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.page = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'page' field has been set.
      * page that has been visited
      * @return True if the 'page' field has been set, false otherwise.
      */
    public boolean hasPage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'page' field.
      * page that has been visited
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder clearPage() {
      page = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * time of the aggregated window
      * @return The value.
      */
    public java.lang.Long getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * time of the aggregated window
      * @param value The value of 'date'.
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder setDate(long value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * time of the aggregated window
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date' field.
      * time of the aggregated window
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder clearDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * duration of the aggregation
      * @return The value.
      */
    public java.lang.Integer getDuration() {
      return duration;
    }

    /**
      * Sets the value of the 'duration' field.
      * duration of the aggregation
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder setDuration(int value) {
      validate(fields()[2], value);
      this.duration = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * duration of the aggregation
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'duration' field.
      * duration of the aggregation
      * @return This builder.
      */
    public io.confluent.dabz.model.VisitEventAggregatedValue.Builder clearDuration() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VisitEventAggregatedValue build() {
      try {
        VisitEventAggregatedValue record = new VisitEventAggregatedValue();
        record.page = fieldSetFlags()[0] ? this.page : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.Long) defaultValue(fields()[1]);
        record.duration = fieldSetFlags()[2] ? this.duration : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VisitEventAggregatedValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<VisitEventAggregatedValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VisitEventAggregatedValue>
    READER$ = (org.apache.avro.io.DatumReader<VisitEventAggregatedValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
