apiVersion: v1
kind: ConfigMap
metadata:
  name: injector-conf
data:
  kafka.properties: |
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap.servers=X
    security.protocol=SASL_SSL
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='X' password='X';
    sasl.mechanism=PLAIN
    # Required for correctness in Apache Kafka clients prior to 2.6
    client.dns.lookup=use_all_dns_ips
    # Best practice for higher availability in Apache Kafka clients prior to 3.0
    session.timeout.ms=45000
    # Required connection configs for Confluent Cloud Schema Registry
    schema.registry.url=X
    basic.auth.credentials.source=USER_INFO
    basic.auth.user.info=X
    linger.ms=500
    batch.size=921600
    compression.type=snappy
    acks=1
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: injector
spec:
  replicas: 20
  selector:
    matchLabels:
      app: injector
  template:
    metadata:
      labels:
        app: injector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/solutionsarchitect-01/mktx-repo/injector:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        ports:
          - containerPort: 8080
            name: http-web
        volumeMounts:
        - name: config-map
          mountPath: /config
      volumes:
        - name: config-map
          configMap:
            name: injector-conf
